POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jaakko Ykkönen",
  "number": "123-567432"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "333-567432"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Aku Ankka",
  "number": ""
}